name: Docker Compose Actions Workflow
on: push
jobs:
  test-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack on Ubuntu 22.04
        run: docker compose --env-file .env up -d
      - name: Test
        run: docker exec -t project python -c 'import rospy; rospy.init_node("test", anonymous=True)' 

  test-macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack on macOS
        run: docker compose --env-file .env up -d
      - name: Test
        run: docker exec -t project python -c 'import rospy; rospy.init_node("test", anonymous=True)' 
